language: python
python: 3.7
dist: xenial
sudo: true
before_install:
- wget https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
- sudo dpkg -i ripgrep_11.0.1_amd64.deb
install:
- pip -v install .
script:
- python ./tests/test.py
notifications:
  slack:
    secure: h+vFOVGNao1yRCc5LtdAOHyhZRyc8Kt7UBDXqpodEeAWWTzb+2DKIxG6pF65IVMVUgN63+lyrCwv0pivmNIGWdP3VG5UwbPhVrAyS4HtOY5f71IGDumnAtw/acX7Pu7mVUXMcufJv2/cBbB+oz4PWootnkk6UOcEFnTfrag7jBDpPlJgF2XPFL7TiuV3LCDJPkRp8keuU5kBWb4uJMq5ZQJC2BqUmFMQjgcy66PZzeEGskXgf1ry7XHDQ25NM3qiyurf8wqLNVOY7cru/A7OgFFzZ8H8eDVNP+5NJp8RAkBkxkEChtEHeWDq6u89LUpEX40O2xQDskjVMwjepeCcXCDRmj3gC9ftXKUCludcXAXohkKjCdcJMgzSSQMPkhlyRs8SX29NKWz7HHhV3MVZOgXoVwclRcxduccD8IbhSNtHjdPk/qEvPPOOVsiiQimdzyrFT6ET9/51QVttePyM5LrUS3k8SZWQ0B6OI+Yj+BqcltevmAy+MD7J9K5XDRHNpXR9yBb2YajrBNJnOlHyoM/PU6tJ3bZgyqiRBIGDjK5THeBS8N7qP8JhwEsYZKXvVoix43t4hyHsW35Yb4ilbgl1pp8j+my3Y+TTbBFfUt4w54RGPbqq31AjrOEi9AwfCkE0qQC1C4Q8NEeOMP/O3uYy9tb3kSaiPMRO7St6jnI=
    on_success: always
    on_failure: always
deploy:
  provider: pypi
  user: securisec
  password:
    secure: NKq9VUv9wPp8QT51kBhxPW4wfX4C4/O+3MeWJqwDcBY+ScG/vjZ3I6ys5MD2m/vQ9nbVSDx2M1VgEZdDRZW0lyC7tq6uTFuC9SUucobagNDPxz6HDOucSaBDozZjuhwJ4vkAQw5Vn+kJ4V2pef9J5ct1IBUD9WsRhBkUmAl9jASSPgFd4tOiLcjsKAvBLsPwyVQOa8JEhz/gYy59TDJoIzZ7w+sktqXjZCczKml6A2YwcDuOBfcYxyrk2+ov1tCK361laQKNRKHNAiHtfseHPXha5GoD+ZozIu2ROBs8Gi9zY/TCKS2Klh27hEPvpm28U4V9yMnYaGgSReBencchT6o+xPOWAw9MOxS+JzXusU4C2lRtpkv+e32B9enE9p7ilpOOuA/V1UoVtVRQS6DpPFuIj9g9YN/T6qHM0qF3th6VknxnBuJApVEwhqaeoRRN7nCRJH9Q0wGoFQqpzqR0dnAXffivycompBwNEZlyTcYJqDVA0VfbAg7WN8hlbHI8JDLr2atiTHc+RNBIBSLdpW/tH5rJqzF6FtjTdC/OwR+tKrau+k7qAMGGWR+KXL0pxJxqvvyuG+QbvtfnZ9VyoAJhlo3Q6MwnNEVK2lwGnD0eN1VWl8bK2WxZryL+wXBxxQUGo435tbNmhGf5fVocnHEd/SZNpMbnZ2uMA/6VN3Q=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: securisec/ripgrepy
  skip_existing: true
  skip_cleanup: true