name: tests

on:
  - push
  - pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.1
      with:
        python-version: ${{ matrix.python-version }}

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2.3.4
      - name: setup
        uses: actions/setup-python@v2.2.1
        with:
          python-version: "3.7"
      - name: build
        run: |
          python setup.py sdist
      - name: publish
        uses: pypa/gh-action-pypi-publish@v1.4.2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
